SELECT 
    TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SUM(SALES_AMOUNT) SALES_AMOUNT
FROM(
    SELECT 
        SALES_DATE, 
        PRODUCT_ID, 
        USER_ID, 
        SALES_AMOUNT
FROM ONLINE_SALE  
UNION ALL 
SELECT
    SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
)
WHERE TO_CHAR(SALES_DATE, 'YYYYMMDD') LIKE '202203%'
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;



