SELECT 
    R.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    R.FAVORITES
FROM REST_INFO R RIGHT JOIN
(       SELECT 
            FOOD_TYPE,
            MAX(FAVORITES) FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
) A ON R.FOOD_TYPE = A.FOOD_TYPE 
AND R.FAVORITES = A.FAVORITES
ORDER BY FOOD_TYPE DESC