SELECT
    REST.REST_ID, 
    REST.REST_NAME, 
    REST.FOOD_TYPE,
    REST.FAVORITES, 
    REST.ADDRESS,
    ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AVERAGE
FROM REST_INFO REST, REST_REVIEW REVIEW
WHERE REST.REST_ID = REVIEW.REST_ID
AND REST.ADDRESS LIKE '서울%'
GROUP BY REST.REST_ID, REST.REST_NAME, REST.FOOD_TYPE, REST.FAVORITES, REST.ADDRESS
ORDER BY AVERAGE DESC, FAVORITES DESC