SELECT
BOARD.TITLE, 
BOARD.BOARD_ID, 
REPLY.REPLY_ID, 
REPLY.WRITER_ID, 
REPLY.CONTENTS,
TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD') CREATED_AT
FROM 
USED_GOODS_BOARD BOARD, 
USED_GOODS_REPLY REPLY
WHERE BOARD.BOARD_ID = REPLY.BOARD_ID
AND TO_CHAR(BOARD.CREATED_DATE, 'YYYYMMDD') LIKE '202210%'
ORDER BY TO_CHAR(REPLY.CREATED_DATE, 'YYYYMMDD'), BOARD.TITLE;


